package book.store.entity;

import java.util.HashSet;
import java.util.Set;

import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToMany;
import jakarta.persistence.ManyToOne;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/* @Entity: This annotation is part of the Java Persistence API (JPA). It 
 * indicates that the class Customer is an entity and is mapped to a database table.
 * 
 * @Data: generates all the boilerplate code that is typically associated with simple Java objects
 * 
 * public class Customer {: This line declares a public Java class named Customer
 */

@Entity
@Data
public class Customer {

/* @Id: This annotation indicates that the field customer Id is the primary key of the entity
 * 
 * @GeneratedValue(strategy = GenerationType.IDENTITY): This annotation specifies that the value
 * of the primary key should be automatically generated by the database
 */
	
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
	
/* The code defines part of an entity class with fields for storing a customers's ID, first name,
 * last name, and email address. 
 */

	private Long customerId;
	private String customerFirstName;
	private String customerLastName;
	private String customerEmail;
	

/* @EqualsAndHashCode.Exclude: This annotation is from the Lombok library. It indicates that the bookStores 
 * field should be excluded from the equals() and hashCode() methods generated by Lombok. 
 * 
 * @ToString.Exclude: Also from Lombok, this annotation specifies that the bookStores field should be 
 * excluded from the toString() method generated by Lombok.
 * 
 * @ManyToMany(mappedBy = "customers", cascade = CascadeType.PERSIST): This is a JPA annotation that defines
 * a many-to-many relationship between the current entity and the BookStore entity. The mappedBy attribute 
 * indicates that the BookStore entity owns the relationship, its customers field. 
 * The cascade = CascadeType.PERSIST setting means that when the current entity is persisted, any associated BookStore
 * entities will also be persisted.
 * 
 * private Set<BookStore> bookStores = new HashSet<>();: This line declares a private field named bookStores of 
 * type Set<BookStore>, which is initialized as a new HashSet.
 * 
 */	
	
@EqualsAndHashCode.Exclude
@ToString.Exclude
@ManyToMany(mappedBy = "customers", cascade = CascadeType.PERSIST)
	private Set<BookStore> bookStores = new HashSet<>();
}
