package book.store.entity;

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.CascadeType;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.OneToMany;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.ToString;

/* @Entity: This annotation is part of the Java Persistence API (JPA). It 
 * indicates that the class Publisher is an entity and is mapped to a database table.
 * 
 * @Data: generates all the boilerplate code that is typically associated with simple Java objects
 * 
 * public class Publisher {: This line declares a public Java class named Publisher
 */

@Entity
@Data
public class Publisher {

/* @Id: This annotation indicates that the field publisherId is the primary key of the entity
 * 
 * @GeneratedValue(strategy = GenerationType.IDENTITY): This annotation specifies that the value
 * of the primary key should be automatically generated by the database
 */
	
@Id
@GeneratedValue(strategy = GenerationType.IDENTITY)
	
 /* The code defines part of an entity class with fields for storing a publisher's ID, name,
  * phone number, and email address. 
  */

    private Long publisherId;
	private String publisherName;
	private String publisherPhone;
	private String publisherEmail;

/* @EqualsAndHashCode.Exclude: This annotation is from the Lombok library. It indicates that the 
 * bookStores field should be excluded from the equals and hashCode methods generated by Lombok.
 * 
 * @ToString.Exclude: Also from Lombok, this annotation specifies that the bookStores field 
 * should be excluded from the toString method generated by Lombok.
 * 
 * @OneToMany(mappedBy= "publisher", cascade = CascadeType.PERSIST): This is a JPA annotation that defines a 
 * one-to-many relationship between the current entity and the BookStore entity.
 * The publisher field in the BookStore entity owns the relationship. 
 * 	
 * This line declares a private field bookStores of type Set<BookStore>, initialized as a new HashSet. 
 * This collection will hold the BookStore entities associated with the current entity.
 */
	
@EqualsAndHashCode.Exclude
@ToString.Exclude
@OneToMany(mappedBy= "publisher", cascade = CascadeType.PERSIST)
private Set<BookStore> bookStores = new HashSet<>();
}
